#pragma once

#include "test_ir_pipeline_validation_helpers.h"

struct DirectCallStatementFixtures {
  primec::Expr methodStmt;
  primec::Definition methodDef;
  primec::Expr defStmt;
  primec::Definition def;
  primec::Expr valuesFactoryCall;
  primec::Expr keyArg;
  primec::Expr valueArg;
  primec::Expr mapInsertStmt;
  primec::Definition mapValuesFactoryDef;
  primec::Transform mapValuesFactoryReturn;
  primec::Definition mapValuesRefFactoryDef;
  primec::Transform mapValuesRefFactoryReturn;
  primec::Definition mapInsertBuiltinDef;
  primec::Definition mapInsertMethodDef;
  primec::Definition mapInsertAliasDef;
  primec::Definition mapInsertGeneratedBareDef;
  primec::Definition mapInsertGeneratedAliasBareDef;
  primec::Definition mapInsertGeneratedPascalAliasBareDef;
  primec::Definition mapInsertGeneratedPascalRefAliasBareDef;
  primec::Definition mapAtArgsPackDef;
  primec::Definition mapAtArgsPackRefDef;
  primec::Definition mapAtArgsPackUnsafeDef;
  primec::Definition mapAtArgsPackUnsafeRefDef;
  primec::Definition mapAtAliasArgsPackDef;
  primec::Definition mapAtUnsafeAliasArgsPackDef;
  primec::Definition mapAtRefAliasArgsPackDef;
  primec::Definition mapAtUnsafeRefAliasArgsPackDef;
  primec::Expr mapInsertMethodValuesParam;
  primec::Transform mapInsertMethodMutTransform;
  primec::Transform mapInsertMethodTypeTransform;
  primec::Expr mapAtArgsPackValuesParam;
  primec::Transform mapAtArgsPackValuesTypeTransform;
  primec::Expr namespacedMapInsertStmt;
  primec::Expr mapInsertMethodStmt;
  primec::Expr holderName;
  primec::Expr holderValuesFieldExpr;
  primec::Expr mapInsertFieldAccessStmt;
  primec::Expr mapInsertFieldAccessInferredStmt;
  primec::Expr mapInsertFieldAccessAliasInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedBareInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedAliasBareInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt;
  primec::Expr mapInsertFieldAccessMethodStmt;
  primec::Expr mapInsertFieldAccessGeneratedAliasMethodStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasMethodStmt;
  primec::Expr mapInsertFieldAccessGeneratedAliasSlashMethodStmt;
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasSlashMethodStmt;
  primec::Expr localMapValuesName;
  primec::Expr localMapValuesLocationExpr;
  primec::ir_lowerer::LocalMap localMapLocals;
  primec::ir_lowerer::LocalInfo localMapInfo;
  primec::Expr mapInsertLocationLocalMapInferredStmt;
  primec::Expr mapInsertLocationLocalMapMethodStmt;
  primec::Expr mapsPackName;
  primec::Expr mapsPackSlotIndex;
  primec::Expr mapsPackAtExpr;
  primec::Expr mapsPackAtLocationExpr;
  primec::Expr mapsPackAtLocationDerefExpr;
  primec::Expr mapsPackAtNestedLocationDerefExpr;
  primec::ir_lowerer::LocalMap mapsPackLocals;
  primec::ir_lowerer::LocalInfo mapsPackInfo;
  primec::Expr mapInsertArgsPackWrappedInferredStmt;
  primec::Expr mapInsertArgsPackWrappedMethodStmt;
  primec::Expr mapsPackReceiverLocationExpr;
  primec::Expr mapsPackAtWrappedReceiverExpr;
  primec::Expr mapInsertArgsPackReceiverLocationInferredStmt;
  primec::Expr mapInsertArgsPackReceiverLocationMethodStmt;
  primec::Expr holderMapsPackFieldExpr;
  primec::Expr holderMapsPackFieldLocationExpr;
  primec::Expr mapsPackAtNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtRefDirectNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeRefDirectNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtRefBareNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt;
  primec::Expr mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt;
  primec::Expr mapsPackAtAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtPascalMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  primec::Expr mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  primec::Expr mapsPackMapAtMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtRefMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackMapAtRefMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt;
  primec::Expr mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  primec::Expr valuesFactoryLocationExpr;
  primec::Expr mapInsertLocationHelperInferredStmt;
  primec::Expr mapInsertLocationHelperMethodStmt;
  primec::Expr holderValuesLocationExpr;
  primec::Expr mapInsertLocationFieldAccessInferredStmt;
  primec::Expr mapInsertLocationFieldAccessMethodStmt;
  primec::Expr valuesRefFactoryCall;
  primec::Expr valuesRefDerefExpr;
  primec::Expr valuesRefLocationExpr;
  primec::Expr valuesRefLocationDerefExpr;
  primec::Expr valuesRefNestedLocationDerefExpr;
  primec::Expr mapInsertNestedLocationDerefHelperStmt;
  primec::Expr mapInsertNestedLocationDerefHelperMethodStmt;
  primec::Expr mapInsertDerefHelperStmt;
  primec::Expr mapInsertDerefHelperMethodStmt;
  primec::Expr holderValuesRefFieldExpr;
  primec::Expr holderValuesRefDerefExpr;
  primec::Expr holderValuesRefLocationExpr;
  primec::Expr holderValuesRefLocationDerefExpr;
  primec::Expr holderValuesRefNestedLocationDerefExpr;
  primec::Expr mapInsertNestedLocationDerefFieldAccessStmt;
  primec::Expr mapInsertNestedLocationDerefFieldAccessMethodStmt;
  primec::Expr mapInsertDerefFieldAccessInferredStmt;
  primec::Expr mapInsertDerefFieldAccessMethodStmt;
};

inline DirectCallStatementFixtures loadDirectCallStatementFixtures() {
  DirectCallStatementFixtures result;
  primec::Expr methodStmt;
  methodStmt.kind = primec::Expr::Kind::Call;
  methodStmt.name = "write";
  methodStmt.isMethodCall = true;
  primec::Definition methodDef;
  methodDef.fullPath = "/main/Writer.write";
  primec::Expr defStmt;
  defStmt.kind = primec::Expr::Kind::Call;
  defStmt.name = "/main/f";
  primec::Definition def;
  def.fullPath = "/main/f";
  primec::Expr valuesFactoryCall;
  valuesFactoryCall.kind = primec::Expr::Kind::Call;
  valuesFactoryCall.name = "/main/makeValues";
  primec::Expr keyArg;
  keyArg.kind = primec::Expr::Kind::Literal;
  keyArg.literalValue = 1;
  keyArg.intWidth = 32;
  primec::Expr valueArg;
  valueArg.kind = primec::Expr::Kind::Literal;
  valueArg.literalValue = 4;
  valueArg.intWidth = 32;
  primec::Expr mapInsertStmt;
  mapInsertStmt.kind = primec::Expr::Kind::Call;
  mapInsertStmt.name = "/std/collections/map/insert";
  mapInsertStmt.args = {valuesFactoryCall, keyArg, valueArg};
  mapInsertStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertStmt.templateArgs = {"i32", "i32"};
  primec::Definition mapValuesFactoryDef;
  mapValuesFactoryDef.fullPath = "/main/makeValues";
  primec::Transform mapValuesFactoryReturn;
  mapValuesFactoryReturn.name = "return";
  mapValuesFactoryReturn.templateArgs = {"map<i32, i32>"};
  mapValuesFactoryDef.transforms.push_back(mapValuesFactoryReturn);
  primec::Definition mapValuesRefFactoryDef;
  mapValuesRefFactoryDef.fullPath = "/main/makeValuesRef";
  primec::Transform mapValuesRefFactoryReturn;
  mapValuesRefFactoryReturn.name = "return";
  mapValuesRefFactoryReturn.templateArgs = {"Reference<map<i32, i32>>"};
  mapValuesRefFactoryDef.transforms.push_back(mapValuesRefFactoryReturn);
  primec::Definition mapInsertBuiltinDef;
  mapInsertBuiltinDef.fullPath = "/std/collections/map/insert_builtin";
  primec::Definition mapInsertMethodDef;
  mapInsertMethodDef.fullPath = "/std/collections/map/insert";
  primec::Definition mapInsertAliasDef;
  mapInsertAliasDef.fullPath = "/std/collections/mapInsert";
  primec::Definition mapInsertGeneratedBareDef;
  mapInsertGeneratedBareDef.fullPath = "/insert__generated";
  primec::Definition mapInsertGeneratedAliasBareDef;
  mapInsertGeneratedAliasBareDef.fullPath = "/mapInsert__generated";
  primec::Definition mapInsertGeneratedPascalAliasBareDef;
  mapInsertGeneratedPascalAliasBareDef.fullPath = "/MapInsert__generated";
  primec::Definition mapInsertGeneratedPascalRefAliasBareDef;
  mapInsertGeneratedPascalRefAliasBareDef.fullPath = "/MapInsertRef__generated";
  primec::Definition mapAtArgsPackDef;
  mapAtArgsPackDef.fullPath = "/map/at";
  primec::Definition mapAtArgsPackRefDef;
  mapAtArgsPackRefDef.fullPath = "/map/at_ref";
  primec::Definition mapAtArgsPackUnsafeDef;
  mapAtArgsPackUnsafeDef.fullPath = "/map/at_unsafe";
  primec::Definition mapAtArgsPackUnsafeRefDef;
  mapAtArgsPackUnsafeRefDef.fullPath = "/map/at_unsafe_ref";
  primec::Definition mapAtAliasArgsPackDef;
  mapAtAliasArgsPackDef.fullPath = "/std/collections/mapAt";
  primec::Definition mapAtUnsafeAliasArgsPackDef;
  mapAtUnsafeAliasArgsPackDef.fullPath = "/std/collections/mapAtUnsafe";
  primec::Definition mapAtRefAliasArgsPackDef;
  mapAtRefAliasArgsPackDef.fullPath = "/std/collections/mapAtRef";
  primec::Definition mapAtUnsafeRefAliasArgsPackDef;
  mapAtUnsafeRefAliasArgsPackDef.fullPath = "/std/collections/mapAtUnsafeRef";
  primec::Expr mapInsertMethodValuesParam;
  mapInsertMethodValuesParam.kind = primec::Expr::Kind::Name;
  mapInsertMethodValuesParam.name = "values";
  primec::Transform mapInsertMethodMutTransform;
  mapInsertMethodMutTransform.name = "mut";
  primec::Transform mapInsertMethodTypeTransform;
  mapInsertMethodTypeTransform.name = "map";
  mapInsertMethodTypeTransform.templateArgs = {"i32", "i32"};
  mapInsertMethodValuesParam.transforms = {mapInsertMethodMutTransform, mapInsertMethodTypeTransform};
  mapInsertMethodDef.parameters = {mapInsertMethodValuesParam};
  mapInsertAliasDef.parameters = {mapInsertMethodValuesParam};
  mapInsertGeneratedBareDef.parameters = {mapInsertMethodValuesParam};
  mapInsertGeneratedAliasBareDef.parameters = {mapInsertMethodValuesParam};
  mapInsertGeneratedPascalAliasBareDef.parameters = {mapInsertMethodValuesParam};
  mapInsertGeneratedPascalRefAliasBareDef.parameters = {mapInsertMethodValuesParam};
  primec::Expr mapAtArgsPackValuesParam;
  mapAtArgsPackValuesParam.kind = primec::Expr::Kind::Name;
  mapAtArgsPackValuesParam.name = "values";
  primec::Transform mapAtArgsPackValuesTypeTransform;
  mapAtArgsPackValuesTypeTransform.name = "args";
  mapAtArgsPackValuesTypeTransform.templateArgs = {"Reference<map<i32, i32>>"};
  mapAtArgsPackValuesParam.transforms = {mapAtArgsPackValuesTypeTransform};
  mapAtArgsPackDef.parameters = {mapAtArgsPackValuesParam};
  mapAtArgsPackRefDef.parameters = {mapAtArgsPackValuesParam};
  mapAtArgsPackUnsafeDef.parameters = {mapAtArgsPackValuesParam};
  mapAtArgsPackUnsafeRefDef.parameters = {mapAtArgsPackValuesParam};
  mapAtAliasArgsPackDef.parameters = {mapAtArgsPackValuesParam};
  mapAtUnsafeAliasArgsPackDef.parameters = {mapAtArgsPackValuesParam};
  mapAtRefAliasArgsPackDef.parameters = {mapAtArgsPackValuesParam};
  mapAtUnsafeRefAliasArgsPackDef.parameters = {mapAtArgsPackValuesParam};
  primec::Expr namespacedMapInsertStmt = mapInsertStmt;
  namespacedMapInsertStmt.name = "insert";
  namespacedMapInsertStmt.namespacePrefix = "/std/collections/map";
  primec::Expr mapInsertMethodStmt = mapInsertStmt;
  mapInsertMethodStmt.name = "insert";
  mapInsertMethodStmt.isMethodCall = true;
  mapInsertMethodStmt.templateArgs.clear();
  primec::Expr holderName;
  holderName.kind = primec::Expr::Kind::Name;
  holderName.name = "holder";
  primec::Expr holderValuesFieldExpr;
  holderValuesFieldExpr.kind = primec::Expr::Kind::Call;
  holderValuesFieldExpr.name = "values";
  holderValuesFieldExpr.isFieldAccess = true;
  holderValuesFieldExpr.args = {holderName};
  holderValuesFieldExpr.argNames = {std::nullopt};
  primec::Expr mapInsertFieldAccessStmt = mapInsertStmt;
  mapInsertFieldAccessStmt.args = {holderValuesFieldExpr, keyArg, valueArg};
  mapInsertFieldAccessStmt.templateArgs = {"i32", "i32"};
  mapInsertFieldAccessStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertFieldAccessInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessAliasInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessAliasInferredStmt.name = "/std/collections/mapInsert";
  mapInsertFieldAccessAliasInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt.name = "/std/collections/MapInsert__generated";
  mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt.name =
      "/std/collections/MapInsertRef__generated";
  mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedBareInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedBareInferredStmt.name = "insert__generated";
  mapInsertFieldAccessGeneratedBareInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedAliasBareInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedAliasBareInferredStmt.name = "mapInsert__generated";
  mapInsertFieldAccessGeneratedAliasBareInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt.name = "MapInsert__generated";
  mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt = mapInsertFieldAccessStmt;
  mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt.name = "MapInsertRef__generated";
  mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt.templateArgs.clear();
  primec::Expr mapInsertFieldAccessMethodStmt;
  mapInsertFieldAccessMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertFieldAccessMethodStmt.name = "insert";
  mapInsertFieldAccessMethodStmt.isMethodCall = true;
  mapInsertFieldAccessMethodStmt.args = {holderValuesFieldExpr, keyArg, valueArg};
  mapInsertFieldAccessMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertFieldAccessGeneratedAliasMethodStmt = mapInsertFieldAccessMethodStmt;
  mapInsertFieldAccessGeneratedAliasMethodStmt.name = "mapInsert__generated";
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasMethodStmt = mapInsertFieldAccessMethodStmt;
  mapInsertFieldAccessGeneratedPascalRefAliasMethodStmt.name = "MapInsertRef__generated";
  primec::Expr mapInsertFieldAccessGeneratedAliasSlashMethodStmt = mapInsertFieldAccessMethodStmt;
  mapInsertFieldAccessGeneratedAliasSlashMethodStmt.name = "/std/collections/mapInsert__generated";
  primec::Expr mapInsertFieldAccessGeneratedPascalRefAliasSlashMethodStmt = mapInsertFieldAccessMethodStmt;
  mapInsertFieldAccessGeneratedPascalRefAliasSlashMethodStmt.name =
      "/std/collections/MapInsertRef__generated";
  primec::Expr localMapValuesName;
  localMapValuesName.kind = primec::Expr::Kind::Name;
  localMapValuesName.name = "valuesLocal";
  primec::Expr localMapValuesLocationExpr;
  localMapValuesLocationExpr.kind = primec::Expr::Kind::Call;
  localMapValuesLocationExpr.name = "location";
  localMapValuesLocationExpr.args = {localMapValuesName};
  localMapValuesLocationExpr.argNames = {std::nullopt};
  primec::ir_lowerer::LocalMap localMapLocals;
  primec::ir_lowerer::LocalInfo localMapInfo;
  localMapInfo.kind = primec::ir_lowerer::LocalInfo::Kind::Value;
  localMapInfo.keyValueKeyKind = primec::ir_lowerer::LocalInfo::ValueKind::Int32;
  localMapInfo.keyValueValueKind = primec::ir_lowerer::LocalInfo::ValueKind::Int32;
  localMapInfo.index = 4;
  localMapLocals.emplace("valuesLocal", localMapInfo);
  primec::Expr mapInsertLocationLocalMapInferredStmt = mapInsertStmt;
  mapInsertLocationLocalMapInferredStmt.args = {localMapValuesLocationExpr, keyArg, valueArg};
  mapInsertLocationLocalMapInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertLocationLocalMapInferredStmt.templateArgs.clear();
  primec::Expr mapInsertLocationLocalMapMethodStmt;
  mapInsertLocationLocalMapMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertLocationLocalMapMethodStmt.name = "insert";
  mapInsertLocationLocalMapMethodStmt.isMethodCall = true;
  mapInsertLocationLocalMapMethodStmt.args = {localMapValuesLocationExpr, keyArg, valueArg};
  mapInsertLocationLocalMapMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackName;
  mapsPackName.kind = primec::Expr::Kind::Name;
  mapsPackName.name = "mapsPack";
  primec::Expr mapsPackSlotIndex;
  mapsPackSlotIndex.kind = primec::Expr::Kind::Literal;
  mapsPackSlotIndex.literalValue = 0;
  mapsPackSlotIndex.intWidth = 32;
  primec::Expr mapsPackAtExpr;
  mapsPackAtExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtExpr.name = "/map/at";
  mapsPackAtExpr.args = {mapsPackName, mapsPackSlotIndex};
  mapsPackAtExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapsPackAtLocationExpr;
  mapsPackAtLocationExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtLocationExpr.name = "location";
  mapsPackAtLocationExpr.args = {mapsPackAtExpr};
  mapsPackAtLocationExpr.argNames = {std::nullopt};
  primec::Expr mapsPackAtLocationDerefExpr;
  mapsPackAtLocationDerefExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtLocationDerefExpr.name = "dereference";
  mapsPackAtLocationDerefExpr.args = {mapsPackAtLocationExpr};
  mapsPackAtLocationDerefExpr.argNames = {std::nullopt};
  primec::Expr mapsPackAtNestedLocationDerefExpr;
  mapsPackAtNestedLocationDerefExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtNestedLocationDerefExpr.name = "location";
  mapsPackAtNestedLocationDerefExpr.args = {mapsPackAtLocationDerefExpr};
  mapsPackAtNestedLocationDerefExpr.argNames = {std::nullopt};
  primec::ir_lowerer::LocalMap mapsPackLocals;
  primec::ir_lowerer::LocalInfo mapsPackInfo;
  mapsPackInfo.isArgsPack = true;
  mapsPackInfo.argsPackElementKind = primec::ir_lowerer::LocalInfo::Kind::Reference;
  mapsPackInfo.keyValueKeyKind = primec::ir_lowerer::LocalInfo::ValueKind::Int32;
  mapsPackInfo.keyValueValueKind = primec::ir_lowerer::LocalInfo::ValueKind::Int32;
  mapsPackLocals.emplace("mapsPack", mapsPackInfo);
  primec::Expr mapInsertArgsPackWrappedInferredStmt = mapInsertStmt;
  mapInsertArgsPackWrappedInferredStmt.args = {mapsPackAtNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertArgsPackWrappedInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackWrappedInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackWrappedMethodStmt;
  mapInsertArgsPackWrappedMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackWrappedMethodStmt.name = "insert";
  mapInsertArgsPackWrappedMethodStmt.isMethodCall = true;
  mapInsertArgsPackWrappedMethodStmt.args = {mapsPackAtNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertArgsPackWrappedMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackReceiverLocationExpr;
  mapsPackReceiverLocationExpr.kind = primec::Expr::Kind::Call;
  mapsPackReceiverLocationExpr.name = "location";
  mapsPackReceiverLocationExpr.args = {mapsPackName};
  mapsPackReceiverLocationExpr.argNames = {std::nullopt};
  primec::Expr mapsPackAtWrappedReceiverExpr;
  mapsPackAtWrappedReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtWrappedReceiverExpr.name = "/map/at";
  mapsPackAtWrappedReceiverExpr.args = {mapsPackReceiverLocationExpr, mapsPackSlotIndex};
  mapsPackAtWrappedReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackReceiverLocationInferredStmt = mapInsertStmt;
  mapInsertArgsPackReceiverLocationInferredStmt.args = {mapsPackAtWrappedReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackReceiverLocationInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackReceiverLocationInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackReceiverLocationMethodStmt;
  mapInsertArgsPackReceiverLocationMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackReceiverLocationMethodStmt.name = "insert";
  mapInsertArgsPackReceiverLocationMethodStmt.isMethodCall = true;
  mapInsertArgsPackReceiverLocationMethodStmt.args = {mapsPackAtWrappedReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackReceiverLocationMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr holderMapsPackFieldExpr;
  holderMapsPackFieldExpr.kind = primec::Expr::Kind::Call;
  holderMapsPackFieldExpr.name = "mapsPack";
  holderMapsPackFieldExpr.isFieldAccess = true;
  holderMapsPackFieldExpr.args = {holderName};
  holderMapsPackFieldExpr.argNames = {std::nullopt};
  primec::Expr holderMapsPackFieldLocationExpr;
  holderMapsPackFieldLocationExpr.kind = primec::Expr::Kind::Call;
  holderMapsPackFieldLocationExpr.name = "location";
  holderMapsPackFieldLocationExpr.args = {holderMapsPackFieldExpr};
  holderMapsPackFieldLocationExpr.argNames = {std::nullopt};
  primec::Expr mapsPackAtNonLocalReceiverExpr;
  mapsPackAtNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtNonLocalReceiverExpr.name = "/map/at";
  mapsPackAtNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackNonLocalReceiverInferredStmt.args = {mapsPackAtNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackNonLocalReceiverMethodStmt;
  mapInsertArgsPackNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackNonLocalReceiverMethodStmt.args = {mapsPackAtNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeNonLocalReceiverExpr;
  mapsPackAtUnsafeNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeNonLocalReceiverExpr.name = "/map/at_unsafe";
  mapsPackAtUnsafeNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt.args = {mapsPackAtUnsafeNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt;
  mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt.args = {mapsPackAtUnsafeNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtRefDirectNonLocalReceiverExpr;
  mapsPackAtRefDirectNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtRefDirectNonLocalReceiverExpr.name = "/map/at_ref";
  mapsPackAtRefDirectNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtRefDirectNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt.args = {mapsPackAtRefDirectNonLocalReceiverExpr,
                                                                   keyArg,
                                                                   valueArg};
  mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt.args = {mapsPackAtRefDirectNonLocalReceiverExpr,
                                                                  keyArg,
                                                                  valueArg};
  mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeRefDirectNonLocalReceiverExpr;
  mapsPackAtUnsafeRefDirectNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeRefDirectNonLocalReceiverExpr.name = "/map/at_unsafe_ref";
  mapsPackAtUnsafeRefDirectNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeRefDirectNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafeRefDirectNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                              std::nullopt};
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeRefDirectNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                            std::nullopt,
                                                                            std::nullopt};
  primec::Expr mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr.name = "/std/collections/mapAtUnsafeRef__generated";
  mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                      std::nullopt};
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                    std::nullopt,
                                                                                    std::nullopt};
  primec::Expr mapsPackAtRefBareNonLocalReceiverExpr;
  mapsPackAtRefBareNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtRefBareNonLocalReceiverExpr.name = "at_ref";
  mapsPackAtRefBareNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtRefBareNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt.args = {mapsPackAtRefBareNonLocalReceiverExpr,
                                                                 keyArg,
                                                                 valueArg};
  mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt.args = {mapsPackAtRefBareNonLocalReceiverExpr,
                                                               keyArg,
                                                               valueArg};
  mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr;
  mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr.name = "mapAtUnsafeRef__generated";
  mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt.args = {
      mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt.name = "insert__generated";
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt.isMethodCall = false;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt.args = {
      mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt.name = "mapInsert__generated";
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt.isMethodCall = false;
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt.args = {
      mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtAliasNonLocalReceiverExpr;
  mapsPackAtAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtAliasNonLocalReceiverExpr.name = "/std/collections/mapAt";
  mapsPackAtAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAliasNonLocalReceiverInferredStmt.args = {mapsPackAtAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAliasNonLocalReceiverMethodStmt.args = {mapsPackAtAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeAliasNonLocalReceiverExpr.name = "/std/collections/mapAtUnsafe";
  mapsPackAtUnsafeAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt.args = {mapsPackAtUnsafeAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt.args = {mapsPackAtUnsafeAliasNonLocalReceiverExpr, keyArg,
                                                                 valueArg};
  mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtMethodAliasNonLocalReceiverExpr;
  mapsPackAtMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtMethodAliasNonLocalReceiverExpr.name = "at";
  mapsPackAtMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt.args = {mapsPackAtMethodAliasNonLocalReceiverExpr, keyArg,
                                                                   valueArg};
  mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt.args = {mapsPackAtMethodAliasNonLocalReceiverExpr, keyArg,
                                                                 valueArg};
  mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr.name = "at_unsafe";
  mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt.args = {mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr,
                                                                         keyArg,
                                                                         valueArg};
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                              std::nullopt};
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtPascalMethodAliasNonLocalReceiverExpr;
  mapsPackAtPascalMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtPascalMethodAliasNonLocalReceiverExpr.name = "At";
  mapsPackAtPascalMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtPascalMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtPascalMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt.args = {mapsPackAtPascalMethodAliasNonLocalReceiverExpr,
                                                                           keyArg,
                                                                           valueArg};
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                std::nullopt};
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtPascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                              std::nullopt,
                                                                              std::nullopt};
  primec::Expr mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr;
  mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr.name = "AtUnsafe";
  mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt,
                                                                                      std::nullopt,
                                                                                      std::nullopt};
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                    std::nullopt,
                                                                                    std::nullopt};
  primec::Expr mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr;
  mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr.name = "AtRef";
  mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                   std::nullopt};
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                 std::nullopt,
                                                                                 std::nullopt};
  primec::Expr mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr.name = "AtUnsafeRef";
  mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt,
                                                                                         std::nullopt,
                                                                                         std::nullopt};
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                       std::nullopt,
                                                                                       std::nullopt};
  primec::Expr mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr;
  mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr.name = "mapAt__generated";
  mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                      std::nullopt};
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                    std::nullopt,
                                                                                    std::nullopt};
  primec::Expr mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.name = "insert__generated";
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.args = {
      mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr.name = "AtUnsafeRef__generated";
  mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr,
                                                                      mapsPackSlotIndex};
  mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt,
                                                                                            std::nullopt,
                                                                                            std::nullopt};
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                          std::nullopt,
                                                                                          std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.kind =
      primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.name = "insert__generated";
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.args = {
      mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt.argNames = {
      std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackMapAtMethodAliasNonLocalReceiverExpr;
  mapsPackMapAtMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtMethodAliasNonLocalReceiverExpr.name = "mapAt";
  mapsPackMapAtMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackMapAtMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt.args = {mapsPackMapAtMethodAliasNonLocalReceiverExpr,
                                                                        keyArg,
                                                                        valueArg};
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                             std::nullopt};
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr;
  mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr.name = "mapAtUnsafe";
  mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                   std::nullopt};
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt,
                                                                                 std::nullopt};
  primec::Expr mapsPackAtRefMethodAliasNonLocalReceiverExpr;
  mapsPackAtRefMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtRefMethodAliasNonLocalReceiverExpr.name = "at_ref";
  mapsPackAtRefMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtRefMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtRefMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt.args = {mapsPackAtRefMethodAliasNonLocalReceiverExpr,
                                                                        keyArg,
                                                                        valueArg};
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                             std::nullopt};
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr.name = "at_unsafe_ref";
  mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                   std::nullopt};
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                 std::nullopt,
                                                                                 std::nullopt};
  primec::Expr mapsPackMapAtRefMethodAliasNonLocalReceiverExpr;
  mapsPackMapAtRefMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtRefMethodAliasNonLocalReceiverExpr.name = "mapAtRef";
  mapsPackMapAtRefMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackMapAtRefMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtRefMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackMapAtRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                std::nullopt};
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt, std::nullopt,
                                                                              std::nullopt};
  primec::Expr mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr.kind = primec::Expr::Kind::Call;
  mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr.name = "mapAtUnsafeRef";
  mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr.isMethodCall = true;
  mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr.args = {holderMapsPackFieldLocationExpr, mapsPackSlotIndex};
  mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr.argNames = {std::nullopt, std::nullopt};
  primec::Expr mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt = mapInsertStmt;
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.args = {
      mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.argNames = {std::nullopt, std::nullopt,
                                                                                      std::nullopt};
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt.templateArgs.clear();
  primec::Expr mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.name = "insert";
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.isMethodCall = true;
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.args = {
      mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr, keyArg, valueArg};
  mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt.argNames = {std::nullopt,
                                                                                    std::nullopt,
                                                                                    std::nullopt};
  primec::Expr valuesFactoryLocationExpr;
  valuesFactoryLocationExpr.kind = primec::Expr::Kind::Call;
  valuesFactoryLocationExpr.name = "location";
  valuesFactoryLocationExpr.args = {valuesFactoryCall};
  valuesFactoryLocationExpr.argNames = {std::nullopt};
  primec::Expr mapInsertLocationHelperInferredStmt = mapInsertStmt;
  mapInsertLocationHelperInferredStmt.args = {valuesFactoryLocationExpr, keyArg, valueArg};
  mapInsertLocationHelperInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertLocationHelperInferredStmt.templateArgs.clear();
  primec::Expr mapInsertLocationHelperMethodStmt;
  mapInsertLocationHelperMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertLocationHelperMethodStmt.name = "insert";
  mapInsertLocationHelperMethodStmt.isMethodCall = true;
  mapInsertLocationHelperMethodStmt.args = {valuesFactoryLocationExpr, keyArg, valueArg};
  mapInsertLocationHelperMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr holderValuesLocationExpr;
  holderValuesLocationExpr.kind = primec::Expr::Kind::Call;
  holderValuesLocationExpr.name = "location";
  holderValuesLocationExpr.args = {holderValuesFieldExpr};
  holderValuesLocationExpr.argNames = {std::nullopt};
  primec::Expr mapInsertLocationFieldAccessInferredStmt = mapInsertStmt;
  mapInsertLocationFieldAccessInferredStmt.args = {holderValuesLocationExpr, keyArg, valueArg};
  mapInsertLocationFieldAccessInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertLocationFieldAccessInferredStmt.templateArgs.clear();
  primec::Expr mapInsertLocationFieldAccessMethodStmt;
  mapInsertLocationFieldAccessMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertLocationFieldAccessMethodStmt.name = "insert";
  mapInsertLocationFieldAccessMethodStmt.isMethodCall = true;
  mapInsertLocationFieldAccessMethodStmt.args = {holderValuesLocationExpr, keyArg, valueArg};
  mapInsertLocationFieldAccessMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr valuesRefFactoryCall;
  valuesRefFactoryCall.kind = primec::Expr::Kind::Call;
  valuesRefFactoryCall.name = "/main/makeValuesRef";
  primec::Expr valuesRefDerefExpr;
  valuesRefDerefExpr.kind = primec::Expr::Kind::Call;
  valuesRefDerefExpr.name = "dereference";
  valuesRefDerefExpr.args = {valuesRefFactoryCall};
  valuesRefDerefExpr.argNames = {std::nullopt};
  primec::Expr valuesRefLocationExpr;
  valuesRefLocationExpr.kind = primec::Expr::Kind::Call;
  valuesRefLocationExpr.name = "location";
  valuesRefLocationExpr.args = {valuesRefFactoryCall};
  valuesRefLocationExpr.argNames = {std::nullopt};
  primec::Expr valuesRefLocationDerefExpr;
  valuesRefLocationDerefExpr.kind = primec::Expr::Kind::Call;
  valuesRefLocationDerefExpr.name = "dereference";
  valuesRefLocationDerefExpr.args = {valuesRefLocationExpr};
  valuesRefLocationDerefExpr.argNames = {std::nullopt};
  primec::Expr valuesRefNestedLocationDerefExpr;
  valuesRefNestedLocationDerefExpr.kind = primec::Expr::Kind::Call;
  valuesRefNestedLocationDerefExpr.name = "location";
  valuesRefNestedLocationDerefExpr.args = {valuesRefLocationDerefExpr};
  valuesRefNestedLocationDerefExpr.argNames = {std::nullopt};
  primec::Expr mapInsertNestedLocationDerefHelperStmt = mapInsertStmt;
  mapInsertNestedLocationDerefHelperStmt.args = {valuesRefNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertNestedLocationDerefHelperStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertNestedLocationDerefHelperStmt.templateArgs.clear();
  primec::Expr mapInsertNestedLocationDerefHelperMethodStmt;
  mapInsertNestedLocationDerefHelperMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertNestedLocationDerefHelperMethodStmt.name = "insert";
  mapInsertNestedLocationDerefHelperMethodStmt.isMethodCall = true;
  mapInsertNestedLocationDerefHelperMethodStmt.args = {valuesRefNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertNestedLocationDerefHelperMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertDerefHelperStmt = mapInsertStmt;
  mapInsertDerefHelperStmt.args = {valuesRefDerefExpr, keyArg, valueArg};
  mapInsertDerefHelperStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertDerefHelperStmt.templateArgs.clear();
  primec::Expr mapInsertDerefHelperMethodStmt;
  mapInsertDerefHelperMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertDerefHelperMethodStmt.name = "insert";
  mapInsertDerefHelperMethodStmt.isMethodCall = true;
  mapInsertDerefHelperMethodStmt.args = {valuesRefDerefExpr, keyArg, valueArg};
  mapInsertDerefHelperMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr holderValuesRefFieldExpr;
  holderValuesRefFieldExpr.kind = primec::Expr::Kind::Call;
  holderValuesRefFieldExpr.name = "valuesRef";
  holderValuesRefFieldExpr.isFieldAccess = true;
  holderValuesRefFieldExpr.args = {holderName};
  holderValuesRefFieldExpr.argNames = {std::nullopt};
  primec::Expr holderValuesRefDerefExpr;
  holderValuesRefDerefExpr.kind = primec::Expr::Kind::Call;
  holderValuesRefDerefExpr.name = "dereference";
  holderValuesRefDerefExpr.args = {holderValuesRefFieldExpr};
  holderValuesRefDerefExpr.argNames = {std::nullopt};
  primec::Expr holderValuesRefLocationExpr;
  holderValuesRefLocationExpr.kind = primec::Expr::Kind::Call;
  holderValuesRefLocationExpr.name = "location";
  holderValuesRefLocationExpr.args = {holderValuesRefFieldExpr};
  holderValuesRefLocationExpr.argNames = {std::nullopt};
  primec::Expr holderValuesRefLocationDerefExpr;
  holderValuesRefLocationDerefExpr.kind = primec::Expr::Kind::Call;
  holderValuesRefLocationDerefExpr.name = "dereference";
  holderValuesRefLocationDerefExpr.args = {holderValuesRefLocationExpr};
  holderValuesRefLocationDerefExpr.argNames = {std::nullopt};
  primec::Expr holderValuesRefNestedLocationDerefExpr;
  holderValuesRefNestedLocationDerefExpr.kind = primec::Expr::Kind::Call;
  holderValuesRefNestedLocationDerefExpr.name = "location";
  holderValuesRefNestedLocationDerefExpr.args = {holderValuesRefLocationDerefExpr};
  holderValuesRefNestedLocationDerefExpr.argNames = {std::nullopt};
  primec::Expr mapInsertNestedLocationDerefFieldAccessStmt = mapInsertStmt;
  mapInsertNestedLocationDerefFieldAccessStmt.args = {holderValuesRefNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertNestedLocationDerefFieldAccessStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertNestedLocationDerefFieldAccessStmt.templateArgs.clear();
  primec::Expr mapInsertNestedLocationDerefFieldAccessMethodStmt;
  mapInsertNestedLocationDerefFieldAccessMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertNestedLocationDerefFieldAccessMethodStmt.name = "insert";
  mapInsertNestedLocationDerefFieldAccessMethodStmt.isMethodCall = true;
  mapInsertNestedLocationDerefFieldAccessMethodStmt.args = {holderValuesRefNestedLocationDerefExpr, keyArg, valueArg};
  mapInsertNestedLocationDerefFieldAccessMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  primec::Expr mapInsertDerefFieldAccessInferredStmt = mapInsertStmt;
  mapInsertDerefFieldAccessInferredStmt.args = {holderValuesRefDerefExpr, keyArg, valueArg};
  mapInsertDerefFieldAccessInferredStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};
  mapInsertDerefFieldAccessInferredStmt.templateArgs.clear();
  primec::Expr mapInsertDerefFieldAccessMethodStmt;
  mapInsertDerefFieldAccessMethodStmt.kind = primec::Expr::Kind::Call;
  mapInsertDerefFieldAccessMethodStmt.name = "insert";
  mapInsertDerefFieldAccessMethodStmt.isMethodCall = true;
  mapInsertDerefFieldAccessMethodStmt.args = {holderValuesRefDerefExpr, keyArg, valueArg};
  mapInsertDerefFieldAccessMethodStmt.argNames = {std::nullopt, std::nullopt, std::nullopt};

  result.methodStmt = methodStmt;
  result.methodDef = methodDef;
  result.defStmt = defStmt;
  result.def = def;
  result.valuesFactoryCall = valuesFactoryCall;
  result.keyArg = keyArg;
  result.valueArg = valueArg;
  result.mapInsertStmt = mapInsertStmt;
  result.mapValuesFactoryDef = mapValuesFactoryDef;
  result.mapValuesFactoryReturn = mapValuesFactoryReturn;
  result.mapValuesRefFactoryDef = mapValuesRefFactoryDef;
  result.mapValuesRefFactoryReturn = mapValuesRefFactoryReturn;
  result.mapInsertBuiltinDef = mapInsertBuiltinDef;
  result.mapInsertMethodDef = mapInsertMethodDef;
  result.mapInsertAliasDef = mapInsertAliasDef;
  result.mapInsertGeneratedBareDef = mapInsertGeneratedBareDef;
  result.mapInsertGeneratedAliasBareDef = mapInsertGeneratedAliasBareDef;
  result.mapInsertGeneratedPascalAliasBareDef = mapInsertGeneratedPascalAliasBareDef;
  result.mapInsertGeneratedPascalRefAliasBareDef = mapInsertGeneratedPascalRefAliasBareDef;
  result.mapAtArgsPackDef = mapAtArgsPackDef;
  result.mapAtArgsPackRefDef = mapAtArgsPackRefDef;
  result.mapAtArgsPackUnsafeDef = mapAtArgsPackUnsafeDef;
  result.mapAtArgsPackUnsafeRefDef = mapAtArgsPackUnsafeRefDef;
  result.mapAtAliasArgsPackDef = mapAtAliasArgsPackDef;
  result.mapAtUnsafeAliasArgsPackDef = mapAtUnsafeAliasArgsPackDef;
  result.mapAtRefAliasArgsPackDef = mapAtRefAliasArgsPackDef;
  result.mapAtUnsafeRefAliasArgsPackDef = mapAtUnsafeRefAliasArgsPackDef;
  result.mapInsertMethodValuesParam = mapInsertMethodValuesParam;
  result.mapInsertMethodMutTransform = mapInsertMethodMutTransform;
  result.mapInsertMethodTypeTransform = mapInsertMethodTypeTransform;
  result.mapAtArgsPackValuesParam = mapAtArgsPackValuesParam;
  result.mapAtArgsPackValuesTypeTransform = mapAtArgsPackValuesTypeTransform;
  result.namespacedMapInsertStmt = namespacedMapInsertStmt;
  result.mapInsertMethodStmt = mapInsertMethodStmt;
  result.holderName = holderName;
  result.holderValuesFieldExpr = holderValuesFieldExpr;
  result.mapInsertFieldAccessStmt = mapInsertFieldAccessStmt;
  result.mapInsertFieldAccessInferredStmt = mapInsertFieldAccessInferredStmt;
  result.mapInsertFieldAccessAliasInferredStmt = mapInsertFieldAccessAliasInferredStmt;
  result.mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt = mapInsertFieldAccessGeneratedPascalAliasPathInferredStmt;
  result.mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt = mapInsertFieldAccessGeneratedPascalRefAliasPathInferredStmt;
  result.mapInsertFieldAccessGeneratedBareInferredStmt = mapInsertFieldAccessGeneratedBareInferredStmt;
  result.mapInsertFieldAccessGeneratedAliasBareInferredStmt = mapInsertFieldAccessGeneratedAliasBareInferredStmt;
  result.mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt = mapInsertFieldAccessGeneratedPascalAliasBareInferredStmt;
  result.mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt = mapInsertFieldAccessGeneratedPascalRefAliasBareInferredStmt;
  result.mapInsertFieldAccessMethodStmt = mapInsertFieldAccessMethodStmt;
  result.mapInsertFieldAccessGeneratedAliasMethodStmt = mapInsertFieldAccessGeneratedAliasMethodStmt;
  result.mapInsertFieldAccessGeneratedPascalRefAliasMethodStmt = mapInsertFieldAccessGeneratedPascalRefAliasMethodStmt;
  result.mapInsertFieldAccessGeneratedAliasSlashMethodStmt = mapInsertFieldAccessGeneratedAliasSlashMethodStmt;
  result.mapInsertFieldAccessGeneratedPascalRefAliasSlashMethodStmt = mapInsertFieldAccessGeneratedPascalRefAliasSlashMethodStmt;
  result.localMapValuesName = localMapValuesName;
  result.localMapValuesLocationExpr = localMapValuesLocationExpr;
  result.localMapLocals = localMapLocals;
  result.localMapInfo = localMapInfo;
  result.mapInsertLocationLocalMapInferredStmt = mapInsertLocationLocalMapInferredStmt;
  result.mapInsertLocationLocalMapMethodStmt = mapInsertLocationLocalMapMethodStmt;
  result.mapsPackName = mapsPackName;
  result.mapsPackSlotIndex = mapsPackSlotIndex;
  result.mapsPackAtExpr = mapsPackAtExpr;
  result.mapsPackAtLocationExpr = mapsPackAtLocationExpr;
  result.mapsPackAtLocationDerefExpr = mapsPackAtLocationDerefExpr;
  result.mapsPackAtNestedLocationDerefExpr = mapsPackAtNestedLocationDerefExpr;
  result.mapsPackLocals = mapsPackLocals;
  result.mapsPackInfo = mapsPackInfo;
  result.mapInsertArgsPackWrappedInferredStmt = mapInsertArgsPackWrappedInferredStmt;
  result.mapInsertArgsPackWrappedMethodStmt = mapInsertArgsPackWrappedMethodStmt;
  result.mapsPackReceiverLocationExpr = mapsPackReceiverLocationExpr;
  result.mapsPackAtWrappedReceiverExpr = mapsPackAtWrappedReceiverExpr;
  result.mapInsertArgsPackReceiverLocationInferredStmt = mapInsertArgsPackReceiverLocationInferredStmt;
  result.mapInsertArgsPackReceiverLocationMethodStmt = mapInsertArgsPackReceiverLocationMethodStmt;
  result.holderMapsPackFieldExpr = holderMapsPackFieldExpr;
  result.holderMapsPackFieldLocationExpr = holderMapsPackFieldLocationExpr;
  result.mapsPackAtNonLocalReceiverExpr = mapsPackAtNonLocalReceiverExpr;
  result.mapInsertArgsPackNonLocalReceiverInferredStmt = mapInsertArgsPackNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackNonLocalReceiverMethodStmt = mapInsertArgsPackNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeNonLocalReceiverExpr = mapsPackAtUnsafeNonLocalReceiverExpr;
  result.mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt = mapInsertArgsPackUnsafeNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt = mapInsertArgsPackUnsafeNonLocalReceiverMethodStmt;
  result.mapsPackAtRefDirectNonLocalReceiverExpr = mapsPackAtRefDirectNonLocalReceiverExpr;
  result.mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt = mapInsertArgsPackAtRefDirectNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt = mapInsertArgsPackAtRefDirectNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeRefDirectNonLocalReceiverExpr = mapsPackAtUnsafeRefDirectNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafeRefDirectNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr = mapsPackAtUnsafeRefGeneratedAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafeRefGeneratedAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtRefBareNonLocalReceiverExpr = mapsPackAtRefBareNonLocalReceiverExpr;
  result.mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt = mapInsertArgsPackAtRefBareNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt = mapInsertArgsPackAtRefBareNonLocalReceiverMethodStmt;
  result.mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr = mapsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverMethodStmt;
  result.mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt = mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedInsertStmt;
  result.mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt = mapInsertArgsPackMapAtUnsafeRefGeneratedBareNonLocalReceiverGeneratedMapInsertStmt;
  result.mapsPackAtAliasNonLocalReceiverExpr = mapsPackAtAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeAliasNonLocalReceiverExpr = mapsPackAtUnsafeAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt = mapInsertArgsPackUnsafeAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt = mapInsertArgsPackUnsafeAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtMethodAliasNonLocalReceiverExpr = mapsPackAtMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr = mapsPackAtUnsafeMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackUnsafeMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtPascalMethodAliasNonLocalReceiverExpr = mapsPackAtPascalMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtPascalMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr = mapsPackAtUnsafePascalMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafePascalMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr = mapsPackAtRefPascalMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtRefPascalMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr = mapsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafeRefPascalMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr = mapsPackMapAtGeneratedMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverMethodStmt;
  result.mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt = mapInsertArgsPackMapAtGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  result.mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr = mapsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverMethodStmt;
  result.mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt = mapInsertArgsPackAtUnsafeRefGeneratedMethodAliasNonLocalReceiverGeneratedInsertMethodStmt;
  result.mapsPackMapAtMethodAliasNonLocalReceiverExpr = mapsPackMapAtMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr = mapsPackMapAtUnsafeMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtUnsafeMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtRefMethodAliasNonLocalReceiverExpr = mapsPackAtRefMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtRefMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtRefMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr = mapsPackAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackMapAtRefMethodAliasNonLocalReceiverExpr = mapsPackMapAtRefMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtRefMethodAliasNonLocalReceiverMethodStmt;
  result.mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr = mapsPackMapAtUnsafeRefMethodAliasNonLocalReceiverExpr;
  result.mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt = mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverInferredStmt;
  result.mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt = mapInsertArgsPackMapAtUnsafeRefMethodAliasNonLocalReceiverMethodStmt;
  result.valuesFactoryLocationExpr = valuesFactoryLocationExpr;
  result.mapInsertLocationHelperInferredStmt = mapInsertLocationHelperInferredStmt;
  result.mapInsertLocationHelperMethodStmt = mapInsertLocationHelperMethodStmt;
  result.holderValuesLocationExpr = holderValuesLocationExpr;
  result.mapInsertLocationFieldAccessInferredStmt = mapInsertLocationFieldAccessInferredStmt;
  result.mapInsertLocationFieldAccessMethodStmt = mapInsertLocationFieldAccessMethodStmt;
  result.valuesRefFactoryCall = valuesRefFactoryCall;
  result.valuesRefDerefExpr = valuesRefDerefExpr;
  result.valuesRefLocationExpr = valuesRefLocationExpr;
  result.valuesRefLocationDerefExpr = valuesRefLocationDerefExpr;
  result.valuesRefNestedLocationDerefExpr = valuesRefNestedLocationDerefExpr;
  result.mapInsertNestedLocationDerefHelperStmt = mapInsertNestedLocationDerefHelperStmt;
  result.mapInsertNestedLocationDerefHelperMethodStmt = mapInsertNestedLocationDerefHelperMethodStmt;
  result.mapInsertDerefHelperStmt = mapInsertDerefHelperStmt;
  result.mapInsertDerefHelperMethodStmt = mapInsertDerefHelperMethodStmt;
  result.holderValuesRefFieldExpr = holderValuesRefFieldExpr;
  result.holderValuesRefDerefExpr = holderValuesRefDerefExpr;
  result.holderValuesRefLocationExpr = holderValuesRefLocationExpr;
  result.holderValuesRefLocationDerefExpr = holderValuesRefLocationDerefExpr;
  result.holderValuesRefNestedLocationDerefExpr = holderValuesRefNestedLocationDerefExpr;
  result.mapInsertNestedLocationDerefFieldAccessStmt = mapInsertNestedLocationDerefFieldAccessStmt;
  result.mapInsertNestedLocationDerefFieldAccessMethodStmt = mapInsertNestedLocationDerefFieldAccessMethodStmt;
  result.mapInsertDerefFieldAccessInferredStmt = mapInsertDerefFieldAccessInferredStmt;
  result.mapInsertDerefFieldAccessMethodStmt = mapInsertDerefFieldAccessMethodStmt;
  return result;
}
