#pragma once

// Runtime support text compiled into every program generated by
// IrToOptCppEmitter. It mirrors the VM's observable behavior: the same fault
// messages (reported as `VM error: ...` with exit code 3), the same heap
// address encoding, the same file-handle packing and I/O error codes. The heap is
// the VM's own allocator (VmHeapCore, pasted in between the two halves below).

namespace primec {

inline constexpr const char *OptCppRuntimeHeaders = R"CPP(#include <algorithm>
#include <bit>
#include <cerrno>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <string>
#include <iterator>
#include <map>
#include <set>
#include <unistd.h>
#include <utility>
#include <vector>

namespace {
)CPP";

// Follows VmHeapCoreSource.
inline constexpr const char *OptCppRuntimePreamble = R"CPP(
constexpr uint64_t PsHeapTag = uint64_t{1} << 63;
constexpr uint64_t PsSlotBytes = 16;
constexpr unsigned PsMaxCallDepth = 4096;
constexpr uint32_t PsFileReadEof = 65536u;

struct Rt {
  int argc;
  char **argv;
  unsigned depth;
  VmHeapCore heap;
};

[[noreturn]] void ps_fault(const char *message) {
  std::fflush(stdout);
  std::fprintf(stderr, "VM error: %s\n", message);
  std::fflush(stderr);
  std::exit(3);
}

[[noreturn]] void ps_fault(const std::string &message) {
  ps_fault(message.c_str());
}

struct PsString {
  const char *data;
  size_t size;
};

inline float ps_f32(uint64_t raw) { return std::bit_cast<float>(static_cast<uint32_t>(raw)); }
inline uint64_t ps_slot_f32(float value) { return static_cast<uint64_t>(std::bit_cast<uint32_t>(value)); }
inline double ps_f64(uint64_t raw) { return std::bit_cast<double>(raw); }
inline uint64_t ps_slot_f64(double value) { return std::bit_cast<uint64_t>(value); }
inline int64_t ps_s64(uint64_t value) { return static_cast<int64_t>(value); }

inline uint64_t ps_div_s64(uint64_t lhs, uint64_t rhs) {
  const int64_t divisor = ps_s64(rhs);
  if (divisor == 0) {
    ps_fault("division by zero in IR");
  }
  if (divisor == -1) {
    return uint64_t{0} - lhs;
  }
  return static_cast<uint64_t>(ps_s64(lhs) / divisor);
}

inline uint64_t ps_div_u64(uint64_t lhs, uint64_t rhs) {
  if (rhs == 0) {
    ps_fault("division by zero in IR");
  }
  return lhs / rhs;
}

inline void ps_emit(const char *text, size_t size, uint64_t flags) {
  FILE *out = (flags & 2) != 0 ? stderr : stdout;
  std::fwrite(text, 1, size, out);
  if ((flags & 1) != 0) {
    std::fputc('\n', out);
  }
}

inline void ps_emit(const std::string &text, uint64_t flags) {
  ps_emit(text.data(), text.size(), flags);
}

// ---- strings -------------------------------------------------------------

inline const PsString &ps_string(const PsString *table, size_t count, uint64_t index) {
  if ((index & PsHeapTag) != 0) {
    ps_fault("invalid dynamic string index in IR");
  }
  if (index >= count) {
    ps_fault("invalid string index in IR");
  }
  return table[static_cast<size_t>(index)];
}

// ---- heap and indirect addressing ----------------------------------------

inline uint64_t ps_heap_alloc(Rt &rt, uint64_t count) {
  uint64_t address = 0;
  std::string error;
  if (!rt.heap.allocate(count, address, error)) {
    ps_fault(error);
  }
  return address;
}

inline void ps_heap_free(Rt &rt, uint64_t address) {
  std::string error;
  if (!rt.heap.release(address, error)) {
    ps_fault(error);
  }
}

inline uint64_t ps_heap_realloc(Rt &rt, uint64_t address, uint64_t count) {
  uint64_t fresh = 0;
  std::string error;
  if (!rt.heap.reallocate(address, count, fresh, error)) {
    ps_fault(error);
  }
  return fresh;
}

// Resolves a byte address to the slot it names: a tagged heap address, or a
// frame offset in functions that take local addresses.
inline uint64_t *ps_resolve(Rt &rt, uint64_t *frame, size_t frameCount, uint64_t address) {
  if (address % PsSlotBytes != 0) {
    ps_fault("unaligned indirect address in IR: " + std::to_string(address));
  }
  if ((address & PsHeapTag) != 0) {
    uint64_t *slot = rt.heap.slotAt(address);
    if (slot == nullptr) {
      ps_fault("invalid indirect address in IR: " + std::to_string(address));
    }
    return slot;
  }
  const uint64_t index = address / PsSlotBytes;
  if (index >= frameCount) {
    ps_fault("invalid indirect address in IR: " + std::to_string(address));
  }
  return &frame[static_cast<size_t>(index)];
}

// ---- argv ----------------------------------------------------------------

inline void ps_print_argv(Rt &rt, uint64_t rawIndex, uint64_t flags, bool unsafe) {
  const int64_t index = ps_s64(rawIndex);
  if (index < 0 || index >= rt.argc) {
    if (unsafe) {
      return;
    }
    ps_fault("invalid argv index in IR");
  }
  const char *text = rt.argv[index];
  ps_emit(text, std::strlen(text), flags);
}

// ---- files ---------------------------------------------------------------

inline uint32_t ps_io_error() {
  return errno == 0 ? 1u : static_cast<uint32_t>(errno);
}

inline uint64_t ps_pack_handle(int fd) {
  if (fd < 0) {
    return static_cast<uint64_t>(ps_io_error()) << 32;
  }
  return static_cast<uint64_t>(static_cast<uint32_t>(fd));
}

inline int ps_handle_fd(uint64_t handle) {
  return static_cast<int>(handle & 0xffffffffu);
}

// mode: 0 read, 1 write (create, truncate), 2 append (create).
inline uint64_t ps_file_open(const PsString &path, int mode) {
  const int flags = mode == 1 ? (O_WRONLY | O_CREAT | O_TRUNC) : (mode == 2 ? (O_WRONLY | O_CREAT | O_APPEND) : O_RDONLY);
  const std::string text(path.data, path.size);
  return ps_pack_handle(::open(text.c_str(), flags, 0644));
}

inline uint64_t ps_file_close(uint64_t handle) {
  return ::close(ps_handle_fd(handle)) < 0 ? static_cast<uint64_t>(ps_io_error()) : 0u;
}

inline uint64_t ps_file_flush(uint64_t handle) {
  return ::fsync(ps_handle_fd(handle)) < 0 ? static_cast<uint64_t>(ps_io_error()) : 0u;
}

inline uint64_t ps_file_read_byte(uint64_t handle, uint64_t &local) {
  uint8_t value = 0;
  const ssize_t rc = ::read(ps_handle_fd(handle), &value, 1);
  if (rc < 0) {
    return ps_io_error();
  }
  if (rc == 0) {
    return PsFileReadEof;
  }
  local = static_cast<uint64_t>(value);
  return 0;
}

inline uint64_t ps_write_all(uint64_t handle, const void *data, size_t size) {
  const char *cursor = static_cast<const char *>(data);
  size_t remaining = size;
  while (remaining > 0) {
    const ssize_t wrote = ::write(ps_handle_fd(handle), cursor, remaining);
    if (wrote < 0) {
      return ps_io_error();
    }
    if (wrote == 0) {
      return static_cast<uint64_t>(EIO);
    }
    remaining -= static_cast<size_t>(wrote);
    cursor += wrote;
  }
  return 0;
}

inline uint64_t ps_file_write_text(uint64_t handle, const std::string &text) {
  return ps_write_all(handle, text.data(), text.size());
}

inline uint64_t ps_file_write_byte(uint64_t handle, uint64_t raw) {
  const uint8_t value = static_cast<uint8_t>(raw & 0xffu);
  return ps_write_all(handle, &value, 1);
}

inline uint64_t ps_file_write_newline(uint64_t handle) {
  const char newline = '\n';
  return ps_write_all(handle, &newline, 1);
}

} // namespace

)CPP";

} // namespace primec
