#!/usr/bin/env python3
"""Archive finished TODO blocks and keep docs/todo_finished.md a short index (TODO-5366).

Workflow: when a task is finished, append its block to docs/todo_finished.md
below the `<!-- UNARCHIVED -->` marker (or anywhere in a not-yet-split legacy
file), then run this script. It moves the new text *verbatim* into
docs/todo_archive/<YYYY-MM>.md (by the block's `finished_at`, or by the section
header date for legacy sections) and regenerates the index table
(ID -> title -> archive file -> finished_at) in docs/todo_finished.md.

`grep TODO-NNNN docs/todo_finished.md` finds the index row; the block is in the
archive file named there. Run with `--check` (used by CTest) to fail when the
index is stale or unarchived blocks are waiting.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

MARKER = "<!-- UNARCHIVED -->"
INDEX_BEGIN = "<!-- INDEX-BEGIN -->"
INDEX_END = "<!-- INDEX-END -->"
MONTHS = {m: i + 1 for i, m in enumerate(
    "January February March April May June July August September October November December".split())}
HEADER_DATE = re.compile(r"\((\w+) (\d+), (\d{4})\)")
BLOCK_HEAD = re.compile(r"^- (?:\[x\]|✓) (TODO-\d+)[:.]?\s*(.*)$")
FINISHED_AT = re.compile(r"^\s*-?\s*finished_at:\s*(\d{4}-\d{2}-\d{2})", re.MULTILINE)
LEGACY_PREAMBLE_LINES = 6

FRONT_MATTER = """# PrimeStruct Finished TODOs

Finished task blocks live in `docs/todo_archive/<YYYY-MM>.md` (one file per
finish month; `undated.md` holds legacy sections without a date). This file is
an index generated by `scripts/archive_todo_finished.py`; do not edit the table
by hand.

To finish a task: append its block below the marker line at the bottom of this
file, then run `python3 scripts/archive_todo_finished.py`. The block is moved
verbatim into the archive and the index is regenerated. CTest
(`PrimeStruct_todo_finished_index`) fails when the index is stale or blocks
are left unarchived.

"""


def month_key(year: int, month: int) -> str:
    return f"{year:04d}-{month:02d}"


def split_chunks(lines: list[str]) -> list[tuple[str | None, list[str]]]:
    """Splits text into (header-month-or-None, lines) chunks at top-level `**...**` headers."""
    chunks: list[tuple[str | None, list[str]]] = []
    context: str | None = None
    current: list[str] = []
    current_key: str | None = None
    started = False
    for line in lines:
        if line.startswith("**"):
            if started or current:
                chunks.append((current_key, current))
            match = HEADER_DATE.search(line)
            if match and match.group(1) in MONTHS:
                context = month_key(int(match.group(3)), MONTHS[match.group(1)])
            current_key = context
            current = [line]
            started = True
        else:
            current.append(line)
    if current:
        chunks.append((current_key if started else None, current))
    return chunks


def split_headerless_blocks(lines: list[str]) -> list[tuple[str | None, list[str]]]:
    """For text with no section header: one chunk per `- [x] TODO-N` block, dated by finished_at."""
    chunks: list[tuple[str | None, list[str]]] = []
    current: list[str] = []
    for line in lines:
        if BLOCK_HEAD.match(line) and current and any(l.strip() for l in current):
            chunks.append((None, current))
            current = []
        current.append(line)
    if current and any(l.strip() for l in current):
        chunks.append((None, current))
    result = []
    for _, body in chunks:
        match = FINISHED_AT.search("\n".join(body))
        key = match.group(1)[:7] if match else None
        result.append((key, body))
    return result


def archive_name(key: str | None) -> str:
    return f"{key}.md" if key else "undated.md"


def index_rows(archive_dir: Path) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for path in sorted(archive_dir.glob("*.md")):
        lines = path.read_text(encoding="utf-8").split("\n")
        for i, line in enumerate(lines):
            match = BLOCK_HEAD.match(line)
            if not match:
                continue
            title = match.group(2).strip().replace("|", "\\|")
            if len(title) > 110:
                title = title[:107].rstrip() + "..."
            finished = "-"
            for follow in lines[i + 1 : i + 12]:
                if follow.startswith("- "):
                    break
                found = re.match(r"\s*-?\s*finished_at:\s*(\S+)", follow)
                if found:
                    finished = found.group(1)
                    break
            rows.append((match.group(1), title, path.name, finished))
    rows.sort(key=lambda r: (r[0], r[2]))
    return rows


def render_index(rows: list[tuple[str, str, str, str]]) -> str:
    out = [INDEX_BEGIN, "", "| ID | Title | Archive | Finished |", "| --- | --- | --- | --- |"]
    out += [f"| {i} | {t} | [{a}](todo_archive/{a}) | {f} |" for i, t, a, f in rows]
    out += ["", INDEX_END, "", MARKER, ""]
    return "\n".join(out)


def read_state(finished: Path) -> tuple[list[str], bool]:
    """Returns (unarchived lines, was_legacy)."""
    text = finished.read_text(encoding="utf-8") if finished.is_file() else ""
    if MARKER in text:
        return text.split(MARKER, 1)[1].split("\n"), False
    # Legacy single-file layout: everything after the short preamble is unarchived.
    return text.split("\n")[LEGACY_PREAMBLE_LINES:], True


def nonblank_counter(lines: list[str]) -> Counter:
    return Counter(l for l in lines if l.strip())


def archive(root: Path) -> int:
    finished = root / "docs" / "todo_finished.md"
    archive_dir = root / "docs" / "todo_archive"
    archive_dir.mkdir(parents=True, exist_ok=True)
    unarchived, legacy = read_state(finished)
    if not any(l.strip() for l in unarchived):
        chunks: list[tuple[str | None, list[str]]] = []
    elif any(l.startswith("**") for l in unarchived):
        chunks = split_chunks(unarchived)
        # Text before the first header (legacy) or headerless trailing blocks keep their own dates.
        fixed: list[tuple[str | None, list[str]]] = []
        for key, body in chunks:
            fixed.append((key, body))
        chunks = fixed
    else:
        chunks = split_headerless_blocks(unarchived)

    before = nonblank_counter(unarchived)
    moved: Counter = Counter()
    per_file: dict[str, list[str]] = {}
    for key, body in chunks:
        if not any(l.strip() for l in body):
            continue
        per_file.setdefault(archive_name(key), []).extend(body)
        moved.update(nonblank_counter(body))
    if before != moved:
        print("round-trip check failed: lines would be lost or duplicated", file=sys.stderr)
        return 1
    for name, body in sorted(per_file.items()):
        path = archive_dir / name
        existing = path.read_text(encoding="utf-8") if path.is_file() else f"# Finished TODOs - {name[:-3]}\n\n"
        path.write_text(existing.rstrip("\n") + "\n\n" + "\n".join(body).strip("\n") + "\n", encoding="utf-8")

    finished.write_text(FRONT_MATTER + render_index(index_rows(archive_dir)), encoding="utf-8")
    moved_blocks = sum(1 for body in per_file.values() for l in body if BLOCK_HEAD.match(l))
    print(f"archived {moved_blocks} blocks into {len(per_file)} files; "
          f"index now has {len(index_rows(archive_dir))} rows" + (" (split legacy file)" if legacy else ""))
    return 0


def check(root: Path) -> int:
    finished = root / "docs" / "todo_finished.md"
    archive_dir = root / "docs" / "todo_archive"
    text = finished.read_text(encoding="utf-8")
    problems = []
    if MARKER not in text:
        problems.append("docs/todo_finished.md has no UNARCHIVED marker (run scripts/archive_todo_finished.py)")
    else:
        tail = text.split(MARKER, 1)[1]
        if tail.strip():
            problems.append("finished blocks are waiting below the marker; run scripts/archive_todo_finished.py")
    expected = FRONT_MATTER + render_index(index_rows(archive_dir))
    if MARKER in text and text.split(MARKER, 1)[0] + MARKER + "\n" != expected.split(MARKER, 1)[0] + MARKER + "\n":
        problems.append("the generated index is stale; run scripts/archive_todo_finished.py")
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1
    print("todo_finished index is up to date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    return check(root) if args.check else archive(root)


if __name__ == "__main__":
    sys.exit(main())
