#!/usr/bin/env python3
"""Generate tests/TEST_INVENTORY.md from the doctest sources (TODO-5354).

Every `TEST_CASE("name")` under tests/unit/ is listed, grouped by directory and
file, in source order. Run without arguments to rewrite the file, or with
`--check` (used by CTest) to fail when the checked-in inventory is stale.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

CASE_RE = re.compile(r'^\s*TEST_CASE(?:_TEMPLATE|_FIXTURE)?\s*\(\s*"((?:[^"\\]|\\.)*)"', re.MULTILINE)
SOURCE_SUFFIXES = {".cpp", ".h", ".hpp"}


def collect(unit_root: Path) -> dict[str, dict[str, list[str]]]:
    files: dict[Path, list[str]] = {}
    for path in sorted(unit_root.rglob("*")):
        if path.suffix not in SOURCE_SUFFIXES or not path.is_file():
            continue
        names = [m.group(1).replace('\\"', '"') for m in CASE_RE.finditer(path.read_text(encoding="utf-8", errors="replace"))]
        if names:
            files[path] = names
    dirs_with_subdirs = {p.parent.parent for p in files if p.parent != unit_root}
    groups: dict[str, dict[str, list[str]]] = defaultdict(dict)
    for path, names in files.items():
        directory = path.parent
        group = str(directory.relative_to(unit_root)) if directory != unit_root else "root"
        if directory in {d for d in dirs_with_subdirs} or any(d.parent == directory for d in {p.parent for p in files}):
            group = f"{group}/root" if directory != unit_root else "root"
        groups[group][path.name] = names
    return groups


def render(groups: dict[str, dict[str, list[str]]]) -> str:
    total_cases = sum(len(n) for files in groups.values() for n in files.values())
    total_files = sum(len(files) for files in groups.values())
    lines = [
        "# Test Inventory",
        "",
        "Generated by `scripts/generate_test_inventory.py` from `tests/unit/`; do not edit by hand.",
        "",
        f"Total: {total_cases} test cases across {total_files} files.",
        "",
    ]
    for group in sorted(groups):
        files = groups[group]
        count = sum(len(n) for n in files.values())
        lines.append(f"## {group} ({count} tests, {len(files)} files)")
        lines.append("")
        for filename in sorted(files):
            lines.append(f"### {filename}")
            lines.append("")
            lines.extend(f"- {name}" for name in files[filename])
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="fail if tests/TEST_INVENTORY.md is stale")
    args = parser.parse_args()
    root = args.root.resolve()
    inventory = root / "tests" / "TEST_INVENTORY.md"
    rendered = render(collect(root / "tests" / "unit"))
    if args.check:
        current = inventory.read_text(encoding="utf-8") if inventory.is_file() else ""
        if current != rendered:
            print("tests/TEST_INVENTORY.md is stale; run scripts/generate_test_inventory.py", file=sys.stderr)
            return 1
        print("tests/TEST_INVENTORY.md is up to date")
        return 0
    inventory.write_text(rendered, encoding="utf-8")
    print(f"wrote {inventory.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
