#include "embed_fixture_bytecode.h"
#include "embed_fixture_programs.h"
#include "embed_test_support.h"
#include "primec/embed/ScriptEngine.h"

#include "third_party/doctest.h"

#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <string>
#include <thread>
#include <vector>

using primec::embed::Script;
using primec::embed::ScriptEngine;

TEST_SUITE_BEGIN("primestruct.embed.script_engine");

TEST_CASE("embed regenerates fixture bytecode when asked") {
  // Opt-in: PRIMESTRUCT_EMBED_REGEN_FIXTURES=<path to embed_fixture_bytecode.h>
  const char *outPath = std::getenv("PRIMESTRUCT_EMBED_REGEN_FIXTURES");
  if (outPath == nullptr) {
    return;
  }
  ScriptEngine engine;
  std::ofstream out(outPath);
  out << "#pragma once\n\n#include <cstdint>\n#include <vector>\n\n"
         "// Generated by test_embed_script_engine.cpp (PRIMESTRUCT_EMBED_REGEN_FIXTURES).\n"
         "// Index i matches embedPrograms()[i]; the full-library test fails when these drift.\n"
         "inline const std::vector<std::vector<uint8_t>> &embedProgramBytecode() {\n"
         "  static const std::vector<std::vector<uint8_t>> bytes = {\n";
  for (const auto &program : embedPrograms()) {
    const auto script = engine.compileSource("/fixture/" + program.name + ".prime", program.source);
    REQUIRE_MESSAGE(script.valid(), script.diagnostics());
    std::vector<uint8_t> bytes;
    std::string error;
    REQUIRE(script.saveBytecode(bytes, error));
    out << "      {  // " << program.name << "\n";
    for (size_t i = 0; i < bytes.size(); ++i) {
      out << (i % 16 == 0 ? "          " : "") << "0x" << std::hex << (bytes[i] < 16 ? "0" : "") << int(bytes[i])
          << std::dec << ",";
      out << (i % 16 == 15 || i + 1 == bytes.size() ? "\n" : " ");
    }
    out << "      },\n";
  }
  out << "  };\n  return bytes;\n}\n";

  ScriptEngine bundleEngine;
  bundleEngine.exportFunction<int32_t(int32_t, int32_t)>("add");
  bundleEngine.exportFunction<double(int32_t, double)>("scale");
  const auto bundle = bundleEngine.compileSource("/fixture/bundle.prime", embedBundleSource());
  REQUIRE_MESSAGE(bundle.valid(), bundle.diagnostics());
  std::vector<uint8_t> bundleBytes;
  std::string bundleError;
  REQUIRE(bundle.saveBytecode(bundleBytes, bundleError));
  out << "\n// Bundle of embedBundleSource() with exports add and scale.\n"
         "inline const std::vector<uint8_t> &embedBundleBytecode() {\n"
         "  static const std::vector<uint8_t> bytes = {\n";
  for (size_t i = 0; i < bundleBytes.size(); ++i) {
    out << (i % 16 == 0 ? "      " : "") << "0x" << std::hex << (bundleBytes[i] < 16 ? "0" : "") << int(bundleBytes[i])
        << std::dec << ",";
    out << (i % 16 == 15 || i + 1 == bundleBytes.size() ? "\n" : " ");
  }
  out << "  };\n  return bytes;\n}\n";
}

TEST_CASE("embed runs main from in-memory source") {
  ScriptEngine engine;
  const auto script = engine.compileSource("/embed_return_seven.prime", "[return<int>]\nmain() {\n  return(7i32)\n}\n");
  REQUIRE(script.valid());
  const auto result = script.run();
  CHECK(result.ok);
  CHECK(result.exitCode == 7);
  CHECK(result.diagnostics.empty());
}

TEST_CASE("embed every fixture program runs with its expected exit code") {
  ScriptEngine engine;
  for (const auto &program : embedPrograms()) {
    CAPTURE(program.name);
    auto script = engine.compileSource("/fixture/" + program.name + ".prime", program.source);
    REQUIRE_MESSAGE(script.valid(), script.diagnostics());
    bindEmbedFixtureHosts(script);
    const auto result = script.run(program.args);
    CHECK(result.ok);
    CHECK(result.exitCode == program.expectedExit);
  }
}

TEST_CASE("embed fixture bytecode matches a fresh compile") {
  REQUIRE(embedProgramBytecode().size() == embedPrograms().size());
  ScriptEngine engine;
  for (size_t i = 0; i < embedPrograms().size(); ++i) {
    const auto &program = embedPrograms()[i];
    CAPTURE(program.name);
    const auto script = engine.compileSource("/fixture/" + program.name + ".prime", program.source);
    REQUIRE(script.valid());
    std::vector<uint8_t> bytes;
    std::string error;
    REQUIRE(script.saveBytecode(bytes, error));
    CHECK_MESSAGE(bytes == embedProgramBytecode()[i],
                  "refresh with PRIMESTRUCT_EMBED_REGEN_FIXTURES=<path>/embed_fixture_bytecode.h");
  }
}

TEST_CASE("embed bundle fixture matches a fresh compile") {
  ScriptEngine engine;
  engine.exportFunction<int32_t(int32_t, int32_t)>("add");
  engine.exportFunction<double(int32_t, double)>("scale");
  const auto script = engine.compileSource("/fixture/bundle.prime", embedBundleSource());
  REQUIRE_MESSAGE(script.valid(), script.diagnostics());
  std::vector<uint8_t> bytes;
  std::string error;
  REQUIRE(script.saveBytecode(bytes, error));
  CHECK_MESSAGE(bytes == embedBundleBytecode(),
                "refresh with PRIMESTRUCT_EMBED_REGEN_FIXTURES=<path>/embed_fixture_bytecode.h)");
}

TEST_CASE("embed reruns one compiled script with identical results") {
  ScriptEngine engine;
  const auto script = engine.compileSource("/embed_rerun.prime", embedPrograms()[4].source);
  REQUIRE(script.valid());
  for (int i = 0; i < 50; ++i) {
    const auto result = script.run();
    REQUIRE(result.ok);
    CHECK(result.exitCode == 55);
  }
}

TEST_CASE("embed copies of a script are independent and equivalent") {
  ScriptEngine engine;
  const auto original = engine.compileSource("/embed_copy.prime", embedPrograms()[3].source);
  REQUIRE(original.valid());
  const Script copy = original;
  Script assigned;
  CHECK_FALSE(assigned.valid());
  assigned = copy;
  CHECK(copy.run().exitCode == 43);
  CHECK(assigned.run().exitCode == 43);
  CHECK(original.run().exitCode == 43);
}

TEST_CASE("embed default constructed script is invalid and does not run") {
  const Script script;
  CHECK_FALSE(script.valid());
  const auto result = script.run();
  CHECK_FALSE(result.ok);
  CHECK_FALSE(result.diagnostics.empty());
  std::vector<uint8_t> bytes;
  std::string error;
  CHECK_FALSE(script.saveBytecode(bytes, error));
  CHECK_FALSE(error.empty());
}

TEST_CASE("embed passes arguments after the program name") {
  ScriptEngine engine;
  const auto script = engine.compileSource("/embed_args.prime", embedPrograms()[5].source);
  REQUIRE(script.valid());
  CHECK(script.run().exitCode == 1);
  CHECK(script.run({"x"}).exitCode == 2);
  CHECK(script.run({"x", "y", "z"}).exitCode == 4);
}

TEST_CASE("embed exit codes truncate to 32 bits and keep sign") {
  ScriptEngine engine;
  const auto negative = engine.compileSource("/embed_neg.prime", embedPrograms()[2].source);
  REQUIRE(negative.valid());
  CHECK(negative.run().exitCode == -5);
  const auto zero = engine.compileSource("/embed_zero.prime", embedPrograms()[1].source);
  REQUIRE(zero.valid());
  CHECK(zero.run().exitCode == 0);
  const auto big = engine.compileSource("/embed_big.prime", "[return<int>]\nmain() {\n  return(2147483647i32)\n}\n");
  REQUIRE(big.valid());
  CHECK(big.run().exitCode == 2147483647);
}

TEST_CASE("embed compiles a file from disk") {
  const auto dir = embedTestDir("compile_file");
  const auto path = embedWriteFile(dir / "main.prime", "[return<int>]\nmain() {\n  return(21i32)\n}\n");
  ScriptEngine engine;
  const auto script = engine.compileFile(path.string());
  REQUIRE_MESSAGE(script.valid(), script.diagnostics());
  CHECK(script.run().exitCode == 21);
}

TEST_CASE("embed reports a missing file as data") {
  ScriptEngine engine;
  const auto script = engine.compileFile("/definitely/not/here/missing.prime");
  CHECK_FALSE(script.valid());
  CHECK(script.diagnostics().find("failed to read input") != std::string::npos);
}

TEST_CASE("embed resolves relative imports against the source directory") {
  const auto dir = embedTestDir("relative_import");
  embedWriteFile(dir / "helper.prime", "[public i32]\nadd_one([i32] value) {\n  return(value + 1i32)\n}\n");
  const auto mainPath =
      embedWriteFile(dir / "main.prime",
                     "import<\"helper.prime\">\n\n[return<int>]\nmain() {\n  return(add_one(41i32))\n}\n");
  ScriptEngine engine;
  const auto fromFile = engine.compileFile(mainPath.string());
  REQUIRE_MESSAGE(fromFile.valid(), fromFile.diagnostics());
  CHECK(fromFile.run().exitCode == 42);
  // In-memory source uses its name as the base for relative imports.
  const auto fromMemory = engine.compileSource(
      (dir / "virtual_main.prime").string(),
      "import<\"helper.prime\">\n\n[return<int>]\nmain() {\n  return(add_one(1i32))\n}\n");
  REQUIRE_MESSAGE(fromMemory.valid(), fromMemory.diagnostics());
  CHECK(fromMemory.run().exitCode == 2);
}

TEST_CASE("embed honors added import paths") {
  const auto libDir = embedTestDir("import_path_lib");
  embedWriteFile(libDir / "extra.prime", "[public i32]\ntwice([i32] value) {\n  return(value * 2i32)\n}\n");
  ScriptEngine engine;
  engine.addImportPath(libDir.string());
  const auto script = engine.compileSource(
      "/embed_import_path.prime",
      "import<\"extra.prime\">\n\n[return<int>]\nmain() {\n  return(twice(21i32))\n}\n");
  REQUIRE_MESSAGE(script.valid(), script.diagnostics());
  CHECK(script.run().exitCode == 42);
}

TEST_CASE("embed supports an alternate entry path") {
  ScriptEngine engine;
  engine.setEntryPath("/start");
  const auto script = engine.compileSource("/embed_entry.prime", "[return<int>]\nstart() {\n  return(9i32)\n}\n");
  REQUIRE_MESSAGE(script.valid(), script.diagnostics());
  CHECK(script.run().exitCode == 9);
}

TEST_SUITE_END();
