#include "primec/Emitter.h"

#include <sstream>
#include <unordered_map>

namespace primec {
namespace {
bool getBuiltinOperator(const Expr &expr, char &out) {
  if (expr.name.empty()) {
    return false;
  }
  std::string name = expr.name;
  if (!name.empty() && name[0] == '/') {
    name.erase(0, 1);
  }
  if (name.find('/') != std::string::npos) {
    return false;
  }
  if (name == "plus") {
    out = '+';
    return true;
  }
  if (name == "minus") {
    out = '-';
    return true;
  }
  if (name == "multiply") {
    out = '*';
    return true;
  }
  if (name == "divide") {
    out = '/';
    return true;
  }
  return false;
}
} // namespace

std::string Emitter::toCppName(const std::string &fullPath) const {
  std::string name = "ps";
  for (char c : fullPath) {
    if (c == '/') {
      name += "_";
    } else {
      name += c;
    }
  }
  return name;
}

std::string Emitter::emitExpr(const Expr &expr,
                              const std::unordered_map<std::string, std::string> &nameMap) const {
  if (expr.kind == Expr::Kind::Literal) {
    return std::to_string(expr.literalValue);
  }
  if (expr.kind == Expr::Kind::Name) {
    return expr.name;
  }
  std::string full;
  if (!expr.name.empty() && expr.name[0] == '/') {
    full = expr.name;
  } else if (!expr.namespacePrefix.empty()) {
    full = expr.namespacePrefix + "/" + expr.name;
  } else {
    full = "/" + expr.name;
  }
  auto it = nameMap.find(full);
  if (it == nameMap.end()) {
    char op = '\0';
    if (getBuiltinOperator(expr, op) && expr.args.size() == 2) {
      std::ostringstream out;
      out << "(" << emitExpr(expr.args[0], nameMap) << " " << op << " "
          << emitExpr(expr.args[1], nameMap) << ")";
      return out.str();
    }
    return "0";
  }
  std::ostringstream out;
  out << it->second << "(";
  for (size_t i = 0; i < expr.args.size(); ++i) {
    if (i > 0) {
      out << ", ";
    }
    out << emitExpr(expr.args[i], nameMap);
  }
  out << ")";
  return out.str();
}

std::string Emitter::emitCpp(const Program &program, const std::string &entryPath) const {
  std::unordered_map<std::string, std::string> nameMap;
  for (const auto &def : program.definitions) {
    nameMap[def.fullPath] = toCppName(def.fullPath);
  }

  std::ostringstream out;
  out << "// Generated by primec (minimal)\n";
  for (const auto &def : program.definitions) {
    out << "static int " << nameMap[def.fullPath] << "(";
    for (size_t i = 0; i < def.parameters.size(); ++i) {
      if (i > 0) {
        out << ", ";
      }
      out << "int " << def.parameters[i];
    }
    out << ") {\n";
    for (const auto &stmt : def.statements) {
      out << "  " << emitExpr(stmt, nameMap) << ";\n";
    }
    out << "  return " << emitExpr(*def.returnExpr, nameMap) << ";\n";
    out << "}\n";
  }
  out << "int main() { return " << nameMap.at(entryPath) << "(); }\n";
  return out.str();
}

} // namespace primec
