#include "test_compile_run_helpers.h"

#if defined(__APPLE__) && (defined(__arm64__) || defined(__aarch64__))
#include "test_compile_run_collection_conformance_helpers.h"
#include "test_compile_run_container_error_conformance_helpers.h"
#include "test_compile_run_checked_pointer_conformance_helpers.h"
#include "test_compile_run_unchecked_pointer_conformance_helpers.h"

TEST_SUITE_BEGIN("primestruct.compile.run.native_backend.collections");

#include "test_compile_run_native_backend_collections_arrays_and_aliases.h"
#include "test_compile_run_native_backend_collections_canonical_map_helpers.h"
#include "test_compile_run_native_backend_collections_vector_alias_rejects_a.h"
#include "test_compile_run_native_backend_collections_vector_alias_rejects_b.h"
#include "test_compile_run_native_backend_collections_experimental_maps_and_helpers.h"
#include "test_compile_run_native_backend_collections_wrapper_shadow_precedence.h"
#include "test_compile_run_native_backend_collections_wrapper_rejects_maps.h"
#include "test_compile_run_native_backend_collections_wrapper_rejects_vectors.h"
#include "test_compile_run_native_backend_collections_alias_diagnostics_a.h"
#include "test_compile_run_native_backend_collections_alias_diagnostics_b.h"
#include "test_compile_run_native_backend_collections_shims_maps_a.h"
#include "test_compile_run_native_backend_collections_shims_maps_b.h"
#include "test_compile_run_native_backend_collections_shims_maps_c.h"
#include "test_compile_run_native_backend_collections_shims_vectors.h"
#include "test_compile_run_native_backend_collections_shadow_precedence_and_counts.h"
#include "test_compile_run_native_backend_collections_canonical_count_shadows.h"
#include "test_compile_run_native_backend_collections_user_shadow_methods_a.h"
#include "test_compile_run_native_backend_collections_user_shadow_methods_b.h"
#include "test_compile_run_native_backend_collections_auto_inferred_helper_precedence.h"
#include "test_compile_run_native_backend_collections_mutators_and_limits_a.h"
#include "test_compile_run_native_backend_collections_mutators_and_limits_b.h"
#include "test_compile_run_native_backend_collections_map_literals_and_string_keys.h"

TEST_SUITE_END();
#endif
